baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jonas' Blog"
theme = "smol"

# Parameters
[params]
    subtitle = "scribe ergo sum"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/jonasagx"
        weight = 1 

    # [[menu.footer]]
    #     name = "Mastodon"
    #     url = "https://example.com/@user"
    #     weight = 2 

    # [[menu.footer]]
    #     name = "Imprint"
    #     url = "/imprint"
    #     weight = 3 
